FROM node:14-alpine

WORKDIR /

# Install app dependencies
COPY package.json /
#COPY yarn.lock /

# setup node environment
ENV NODE_PATH=/node_modules
ENV PATH=$PATH:$NODE_PATH/.bin

# install packages
RUN yarn

# Create app directory
WORKDIR /app

# Bundle app source
COPY . /app/
