FROM node:14-alpine

WORKDIR /app

# Bundle app source
COPY . /app/

# install packages
RUN apk add git
RUN yarn global add react-scripts heroku
RUN yarn install --production

# Build React app
WORKDIR /app/frontend
RUN yarn install --production
RUN yarn build

# Go back to app root
WORKDIR /app

# copy react build files
RUN mv /app/frontend/build/service-worker.js* /app/assets
RUN mv /app/frontend/build/* /app/public
RUN node /app/deploy/build-frontend.js
RUN rm .env
