version: '3.3'
services:
    mongodb:
        restart: always
    app:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.prod
        command: yarn build
        restart: always
