version: "3.3"
services:
    app:
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - mongodb
    mongodb:
        image: mongo:4.0
        command: mongod --smallfiles
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - db_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
volumes:
    db_data:
